mode: "dev"
db:
  driver: "sqlite3"
  master_dsn: "go-base/resources/go-base.db"
  log: true
  pool:
    max_idle_conns: 0
    max_open_conns: 0
    conn_max_lifetime: 0
sqlite:
  dsn: "go-base/resources/go-base.db"
  log: true